# Generated by Django 3.0.6 on 2020-10-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('shortdesc', models.TextField()),
                ('longdesc', models.TextField()),
                ('area', models.TextField(blank=True, null=True)),
                ('indoors', models.BooleanField(blank=True, null=True)),
                ('exits', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('direction', models.TextField(primary_key=True, serialize=False)),
                ('destination', models.ForeignKey(db_column='destination', on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination', to='api.Room')),
                ('source', models.ForeignKey(db_column='source', on_delete=django.db.models.deletion.DO_NOTHING, related_name='source', to='api.Room')),
            ],
            options={
                'db_table': 'exit',
                'unique_together': {('direction', 'source', 'destination')},
            },
        ),
    ]
